### ISSUE TITLE
when db_rules & tbl_rules use different sharding column, it will start fail.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#178]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The config:

```
kind: ConfigMap
apiVersion: "1.0"
metadata:
  name: arana-config
data:
  listeners:
    - protocol_type: mysql
      server_version: 5.7.0
      socket_address:
        address: 0.0.0.0
        port: 13306

  tenants:
    - name: arana
      users:
        - username: arana
          password: "123456"
        - username: dksl
          password: "123456"

  clusters:
    - name: mall
      type: mysql
      sql_max_limit: -1
      tenant: arana
      conn_props:
        capacity: 10
        max_capacity: 20
        idle_timeout: 60
      groups:
        - name: mall_0
          nodes:
            - name: arana-node-1
              host: arana-mysql
              port: 3307
              username: root
              password: "123456"
              database: mall_0
              weight: r10w10
              labels:
                zone: shanghai
              conn_props:
                readTimeout: "1s"
                writeTimeout: "1s"
                parseTime: true
                loc: Local
                charset: utf8mb4,utf8
        - name: mall_1
          nodes:
            - name: arana-node-1
              host: arana-mysql
              port: 3307
              username: root
              password: "123456"
              database: mall_1
              weight: r10w10
              labels:
                zone: shanghai
              conn_props:
                readTimeout: "1s"
                writeTimeout: "1s"
                parseTime: true
                loc: Local
                charset: utf8mb4,utf8

  sharding_rule:
    tables:
      - name: mall.orders
        allow_full_scan: true
        db_rules:
          - column: user_id
            expr: $value % 2
        tbl_rules:
          - column: user_id
            expr: $value % 4
        topology:
          db_pattern: mall_${0...1}
          tbl_pattern: orders_${0...3}
        attributes:
          sqlMaxLimit: -1
      - name: mall.orders_item
        allow_full_scan: true
        db_rules:
          - column: order_id    // when there is user_id, is OK, start success.
            expr: $value % 2
        tbl_rules:
          - column: user_id
            expr: $value % 4
        topology:
          db_pattern: mall_${0...1}
          tbl_pattern: orders_item_${0...3}
        attributes:
          sqlMaxLimit: -1
```

The error:

```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/dongzonglei/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/qg/zk85p89j08n0h8dk0yg56l580000gp/T/GoLand/___START github.com/arana-db/arana/cmd #gosetup
/private/var/folders/qg/zk85p89j08n0h8dk0yg56l580000gp/T/GoLand/___START start -c ./conf/bootstrap.yaml

   ___   ___  ___   _  _____ 
  / _ | / _ \/ _ | / |/ / _ |
 / __ |/ , _/ __ |/    / __ |
/_/ |_/_/|_/_/ |_/_/|_/_/ |_|
High performance, powerful DB Mesh.
_____________________________________________


2022-05-10T21:40:42.118+0800    DEBUG   file/file.go:99 [ConfigCenter][File] load config content : map[config.PathKey]string{"/arana-db/config/data/dataSourceClusters":"[{\"name\":\"mall\",\"type\":\"mysql\",\"sql_max_limit\":-1,\"tenant\":\"arana\",\"conn_props\":{\"capacity\":10,\"max_capacity\":20,\"idle_timeout\":60},\"groups\":[{\"name\":\"mall_0\",\"nodes\":[{\"name\":\"arana-node-1\",\"host\":\"arana-mysql\",\"port\":3307,\"username\":\"root\",\"password\":\"123456\",\"database\":\"mall_0\",\"conn_props\":{\"charset\":\"utf8mb4,utf8\",\"loc\":\"Local\",\"parseTime\":\"true\",\"readTimeout\":\"1s\",\"writeTimeout\":\"1s\"},\"weight\":\"r10w10\",\"labels\":{\"zone\":\"shanghai\"}}]},{\"name\":\"mall_1\",\"nodes\":[{\"name\":\"arana-node-1\",\"host\":\"arana-mysql\",\"port\":3307,\"username\":\"root\",\"password\":\"123456\",\"database\":\"mall_1\",\"conn_props\":{\"charset\":\"utf8mb4,utf8\",\"loc\":\"Local\",\"parseTime\":\"true\",\"readTimeout\":\"1s\",\"writeTimeout\":\"1s\"},\"weight\":\"r10w10\",\"labels\":{\"zone\":\"shanghai\"}}]}]}]", "/arana-db/config/data/filters":"", "/arana-db/config/data/listeners":"[{\"protocol_type\":\"mysql\",\"socket_address\":{\"address\":\"0.0.0.0\",\"port\":13306},\"server_version\":\"5.7.0\"}]", "/arana-db/config/data/shardingRule":"{\"tables\":[{\"name\":\"mall.orders\",\"allow_full_scan\":true,\"db_rules\":[{\"column\":\"user_id\",\"expr\":\"$value % 2\"}],\"tbl_rules\":[{\"column\":\"user_id\",\"expr\":\"$value % 4\"}],\"topology\":{\"db_pattern\":\"mall_${0...1}\",\"tbl_pattern\":\"orders_${0...3}\"},\"shadow_topology\":null,\"attributes\":{\"sqlMaxLimit\":\"-1\"}},{\"name\":\"mall.orders_item\",\"allow_full_scan\":true,\"db_rules\":[{\"column\":\"order_id\",\"expr\":\"$value % 2\"}],\"tbl_rules\":[{\"column\":\"user_id\",\"expr\":\"$value % 4\"}],\"topology\":{\"db_pattern\":\"mall_${0...1}\",\"tbl_pattern\":\"orders_item_${0...3}\"},\"shadow_topology\":null,\"attributes\":{\"sqlMaxLimit\":\"-1\"}}]}", "/arana-db/config/data/tenants":"[{\"name\":\"arana\",\"users\":[{\"username\":\"arana\",\"password\":\"123456\"},{\"username\":\"dksl\",\"password\":\"123456\"}]}]", "/arana-db/config/metadata":"{\"name\":\"arana-config\"}"}
2022-05-10T21:40:42.119+0800    DEBUG   config/config.go:139    load configuration:
kind: ""
apiVersion: ""
metadata:
    name: arana-config
data:
    filters: []
    listeners:
        - protocol_type: mysql
          socket_address:
            address: 0.0.0.0
            port: 13306
          server_version: 5.7.0
    tenants:
        - name: arana
          users:
            - username: arana
              password: "123456"
            - username: dksl
              password: "123456"
    clusters:
        - name: mall
          type: mysql
          sql_max_limit: -1
          tenant: arana
          conn_props:
            capacity: 10
            max_capacity: 20
            idle_timeout: 60
          groups:
            - name: mall_0
              nodes:
                - name: arana-node-1
                  host: arana-mysql
                  port: 3307
                  username: root
                  password: "123456"
                  database: mall_0
                  conn_props:
                    charset: utf8mb4,utf8
                    loc: Local
                    parseTime: "true"
                    readTimeout: 1s
                    writeTimeout: 1s
                  weight: r10w10
                  labels:
                    zone: shanghai
            - name: mall_1
              nodes:
                - name: arana-node-1
                  host: arana-mysql
                  port: 3307
                  username: root
                  password: "123456"
                  database: mall_1
                  conn_props:
                    charset: utf8mb4,utf8
                    loc: Local
                    parseTime: "true"
                    readTimeout: 1s
                    writeTimeout: 1s
                  weight: r10w10
                  labels:
                    zone: shanghai
    sharding_rule:
        tables:
            - name: mall.orders
              allow_full_scan: true
              db_rules:
                - column: user_id
                  expr: $value % 2
              tbl_rules:
                - column: user_id
                  expr: $value % 4
              topology:
                db_pattern: mall_${0...1}
                tbl_pattern: orders_${0...3}
              shadow_topology: null
              attributes:
                sqlMaxLimit: "-1"
            - name: mall.orders_item
              allow_full_scan: true
              db_rules:
                - column: order_id
                  expr: $value % 2
              tbl_rules:
                - column: user_id
                  expr: $value % 4
              topology:
                db_pattern: mall_${0...1}
                tbl_pattern: orders_item_${0...3}
              shadow_topology: null
              attributes:
                sqlMaxLimit: "-1"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d1fd5a]

goroutine 1 [running]:
github.com/arana-db/arana/pkg/boot.(*discovery).GetTable(0xc000092320, 0x21d0d70, 0xc000048088, 0xc0007a6eb0, 0x4, 0xc0007a70a5, 0xb, 0xc000797668, 0x0, 0x0)
        /Users/dongzonglei/source_code/Github/arana/pkg/boot/discovery.go:385 +0xc3a
github.com/arana-db/arana/pkg/boot.buildNamespace(0x21d0d70, 0xc000048088, 0x21e4120, 0xc000092320, 0xc0007a6eb0, 0x4, 0x0, 0x0, 0x10e8b91)
        /Users/dongzonglei/source_code/Github/arana/pkg/boot/boot.go:121 +0x3e2
github.com/arana-db/arana/pkg/boot.Boot(0x21d0d70, 0xc000048088, 0x21e4120, 0xc000092320, 0xc0005b3c58, 0x1)
        /Users/dongzonglei/source_code/Github/arana/pkg/boot/boot.go:57 +0x4d2
github.com/arana-db/arana/cmd/start.Run(0x7ffeefbffa5a, 0x15)
        /Users/dongzonglei/source_code/Github/arana/cmd/start/start.go:77 +0x11a
github.com/arana-db/arana/cmd/start.run(0xc0002fe280, 0xc0000922e0, 0x0, 0x2)
        /Users/dongzonglei/source_code/Github/arana/cmd/start/start.go:151 +0x245
github.com/spf13/cobra.(*Command).execute(0xc0002fe280, 0xc0000922c0, 0x2, 0x2, 0xc0002fe280, 0xc0000922c0)
        /Users/dongzonglei/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ff400, 0xc0002ff400, 0x0, 0xffffffff)
        /Users/dongzonglei/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/dongzonglei/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /Users/dongzonglei/source_code/Github/arana/cmd/main.go:44 +0x9d

Process finished with the exit code 2
```
