### ISSUE TITLE
[Refactor] refactor config center, according the new config path key.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#346]
**What would you like to be added**:

**Why is this needed**:

- [x]  add `rootPath` config at `bootstrap.xml` & `env`;
- [x]  add `version` config to  `bootstrap.xml`;
- [x]  fix `etcd` client problem, `dubbogo/gost  etcd`  unsuited;
The new config design:

### Root

```azure
ARANA_ROOT=/arana
```

### Tenants 
```yaml
# 路径 Key
${ARANA_ROOT}/v1/tenants/<tenant>
/arana/v1/tenants/arana

# 存储内容
- name: arana
  users:
    - username: root
      password: "123456"
    - username: arana
      password: "123456"
```

### Nodes
```yaml
# 路径 Key
${ARANA_ROOT}/v1/tenants/<tenant>/nodes/<node>
/arana/v1/tenants/arana/nodes/node0
/arana/v1/tenants/arana/nodes/node1

# 存储内容
- name: node0
  host: arana-mysql
  port: 3306
  username: root
  password: "123456"
  database: employees_0000
  weight: r10w10
  parameters:
```

### Data Source Clusters
```yaml
# 路径 Key
${ARANA_ROOT}/v1/tenants/<tenant>/clusters/<cluster>/groups/<group>/nodes/<node>
/arana/v1/tenants/arana/clusters/employees/groups/employees_0000/nodes/node0
/arana/v1/tenants/arana/clusters/employees/groups/employees_0000/nodes/node0_r_0

# 存储内容
- name: node0
  host: arana-mysql
  port: 3306
  username: root
  password: "123456"
  database: employees_0000
  weight: r10w10
  parameters:


# 路径 Key
${ARANA_ROOT}/v1/tenants/<tenant>/clusters/<cluster>/groups/<group>
/arana/v1/tenants/arana/clusters/employees/groups/employees_0000
/arana/v1/tenants/arana/clusters/employees/groups/employees_0001

# 存储内容
nodes:
  - node0
  - node1
```

### Sharding Rule
```yaml
# 路径 Key
${ARANA_ROOT}/v1/tenants/<tenant>/clusters/<cluster>/tables/<table>
/arana/v1/tenants/arana/clusters/employees/tables/student
/arana/v1/tenants/arana/clusters/employees/tables/order

# 存储内容
- name: student
  allow_full_scan: true
  sequence:
    type: snowflake
    option:
  db_rules:
    - column: uid
      type: scriptExpr
      expr: parseInt($value % 32 / 8)
  tbl_rules:
    - column: uid
      type: scriptExpr
      expr: $value % 32
      step: 32
  topology:
    db_pattern: employees_${0000..0003}
    tbl_pattern: student_${0000..0031}
  attributes:
    sqlMaxLimit: -1
```

**Comment by chuntaojun** [comment]
ok

**Comment by chuntaojun** [comment]
新的 config.yaml 文件内容

```yaml
kind: ConfigMap
apiVersion: "1.0"
metadata:
  name: arana-config
data:
  listeners:
    - protocol_type: mysql
      server_version: 5.7.0
      socket_address:
        address: 0.0.0.0
        port: 13306

  tenants:
    tenant:
      - name: arana
        users:
          - username: arana
            password: "123456"
          - username: dksl
            password: "123456"

    clusters:
      - name: employees
        type: mysql
        sql_max_limit: -1
        tenant: arana
        parameters:
          max_allowed_packet: 256M
        groups:
          - name: employees_0000
            nodes:
              - node0
              - node0_r_0
          - name: employees_0001
            nodes:
              - node1
          - name: employees_0002
            nodes:
              - node2
          - name: employees_0003
            nodes:
              - node3
        sharding_rule:
          tables:
            - name: employees.student
              allow_full_scan: true
              sequence:
                type: snowflake
                option:
              db_rules:
                - column: uid
                  type: scriptExpr
                  expr: parseInt($value % 32 / 8)
              tbl_rules:
                - column: uid
                  type: scriptExpr
                  expr: $value % 32
                  step: 32
              topology:
                db_pattern: employees_${0000..0003}
                tbl_pattern: student_${0000..0031}
              attributes:
                sqlMaxLimit: -1
    nodes:
      - id: node0
        name: node0
        host: arana-mysql
        port: 3306
        username: root
        password: "123456"
        database: employees_0000
        weight: r10w10
        parameters:
      - id: node0_r_0
        name: node0_r_0
        host: arana-mysql
        port: 3306
        username: root
        password: "123456"
        database: employees_0000_r
        weight: r0w0
        parameters:
      - id: node1
        name: node1
        host: arana-mysql
        port: 3306
        username: root
        password: "123456"
        database: employees_0001
        weight: r10w10
        parameters:
      - id: node2
        name: node2
        host: arana-mysql
        port: 3306
        username: root
        password: "123456"
        database: employees_0002
        weight: r10w10
        parameters:
      - id: node3
        name: node3
        host: arana-mysql
        port: 3306
        username: root
        password: "123456"
        database: employees_0003
        weight: r10w10
        parameters:


```
