### ISSUE TITLE
[Sharding] Support multiple columns complex sharding key.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#425]
**What would you like to be added**:

**Why is this needed**:

**Comment by jjeffcaii** [comment]
Phases:
1. js script support multiple shard keys, for example: `hash($key1) ^ hash($key2)`
2. ...

@binbin0325 implement phase-1 at first.

**Comment by jjeffcaii** [comment]
I prefer plan 2, but I think we should use `$varname` instead of `varname` directly.

**Comment by binbin0325** [comment]
ok ，maybe it's better that way
```yaml
           tbl_rules:
                type: scriptExpr
                exprs: $uid % 32 , $age %8
                step: 32
```
