### ISSUE TITLE
[Bug] integration test case, when `parameters` not exist, execute error.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#466]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
query_rows_cases:
  - sql: "SELECT name, value FROM sequence WHERE name= ?"
    parameters: "1:string"
    sense:
      - db
    expected:
      type: "file"
      value: "../../config/db/expected.yaml"
  - sql: "SHOW DATABASES"
    parameters: ""
    sense:
      - db
    expected:
      type: "valueString"
      value: "employees"
```

when `parameters: ""`,  the result of `params := strings.Split(sqlCase.Parameters, ",")` is one. 

```
for _, param := range params {
					k, _ := test.GetValueByType(param)
					args = append(args, k)
				}
```
will error.
