### ISSUE TITLE
Should support Role based access control for admin API

### ISSUE THREAD

**Issue by jjeffcaii** [arana-db/arana#540]
**What would you like to be added**:
1. add root user for admin, this configuration can be added into `bootstrap.yaml`, for example:
```yaml
--- bootstrap.yaml
# ...

# just an example, no need to follow this style
admin:
    auth: username:password

```
2. add auth layer for admin APIs over JWT, maybe we can use this lib: https://github.com/appleboy/gin-jwt
3. user can log in as root or a normal tenant user
    - only root role can mutate tenants
    - normal user can mutate all resources belong to the current tenant

**Why is this needed**:
The AranaUI need this feature.
